webtalk_init -webtalk_dir D:/SUSTech/2026 Spring/lab5/Fibonacci/Fibonacci/Fibonacci.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 15 21:22:20 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4125815a-797b-4cdb-9745-bfed0f7daf20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5883fa430f0441dea04fcb6f5f4c833b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) 7 250H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2995 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "139022453 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.76_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2392463461 -regid "" -xml D:/SUSTech/2026 Spring/lab5/Fibonacci/Fibonacci/Fibonacci.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/SUSTech/2026 Spring/lab5/Fibonacci/Fibonacci/Fibonacci.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/SUSTech/2026 Spring/lab5/Fibonacci/Fibonacci/Fibonacci.sim/sim_1/synth/timing/xsim/xsim.dir/testbench_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
